### ISSUE TITLE
Missing correct api group for cluster role

### ISSUE THREAD

**Issue by zenntrix** [guilhem/freeipa-issuer#17]
See below, the api-group does not match that which is in the CRD.

https://github.com/guilhem/freeipa-issuer/blob/d2d33dd10b7d8550caa81f3f58984fa3c300c052/config/rbac/cert_manager_controller_approver_clusterrole.yaml#L8

**Comment by guilhem** [comment]
This is the normal behavior.
For more information, you can have a look at cert-manager doc https://cert-manager.io/docs/concepts/certificaterequest/#approval
or in PR #11 :)
